config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  
  # 一般ユーザー用のルーティング
  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:new, :create, :show, :index, :destroy, :edit]
  resources :relationships, only: [:create, :destroy]

  resources :books, only: [] do  # 個別のアクションは不要
    collection do
      get 'search'
    end
  end

  resources :bookshelves, only: [:index, :create, :update, :destroy]

  # 管理者用のルーティング
  namespace :admin do
    resources :users, only: [:destroy]
  end
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="p-4 mt-3 mb-4 mx-3 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-blue-200 dark:text-blue-800" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="p-4 mt-3 mb-4 mx-3 text-sm text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="bg-gray-800 border-gray-200 px-2 sm:px-4 py-2.5">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <%= link_to "BookRoom", "/", class: "self-center text-white text-xl font-semibold whitespace-nowrap" %>
    <div class="w-full md:block md:w-auto">
      <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
        <li>
          <%= link_to "投稿一覧", root_path, class: "block py-2 pr-4 pl-3 text-gray-400 hover:text-white border-b border-gray-700 hover:bg-gray-700 md:hover:bg-transparent md:border-0 md:hover:text-blue-white md:p-0" %>
        </li>
        <% if current_user %>

          <li>
            <%= link_to "ログ投稿", new_post_path, class: "block py-2 pr-4 pl-3 text-gray-400 hover:text-white border-b border-gray-700 hover:bg-gray-700 md:hover:bg-transparent md:border-0 md:hover:text-blue-white md:p-0" %>
          </li>
          <li>
            <%= button_to "ログアウト", destroy_user_session_path, class: "block py-2 pr-4 pl-3 text-gray-400 hover:text-white border-b border-gray-700 hover:bg-gray-700 md:hover:bg-transparent md:border-0 md:hover:text-blue-white md:p-0", method: :delete %>
          </li>

        <% else %>

          <li>
            <%= link_to "ユーザー登録", new_user_registration_path, class: "block py-2 pr-4 pl-3 text-gray-400 hover:text-white border-b border-gray-700 hover:bg-gray-700 md:hover:bg-transparent md:border-0 md:hover:text-blue-white md:p-0" %>
          </li>
          <li>
            <%= link_to "ログイン", new_user_session_path, class: "block py-2 pr-4 pl-3 text-gray-400 hover:text-white border-b border-gray-700 hover:bg-gray-700 md:hover:bg-transparent md:border-0 md:hover:text-blue-white md:p-0" %>
          </li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="flex space-x-4 md:space-x-8 my-2 md:my-4">
  <%= link_to following_user_path(@user), 
      class: "text-center text-gray-600 hover:text-blue-600 hover:no-underline" do %>
    <strong id="following" class="block text-lg md:text-xl">
      <%= @user.following.count %>
    </strong>
    <span class="text-xs md:text-sm">following</span>
  <% end %>
  
  <%= link_to followers_user_path(@user), 
      class: "text-center text-gray-600 hover:text-blue-600 hover:no-underline" do %>
    <strong id="followers" class="block text-lg md:text-xl">
      <%= @user.followers.count %>
    </strong>
    <span class="text-xs md:text-sm">followers</span>
  <% end %>
</div>